global:
  scrape_interval:     1s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'target'
    static_configs:
      - targets: ["127.0.0.1:9898", "127.0.0.2:9898", "127.0.0.3:9898", "127.0.0.4:9898"]
