image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

.rust_template: &rust_template
  before_script:
    - rustc --version && cargo --version
  only: 
    - merge_request
  cache:
    paths:
      - target/
      - cargo/

stages:
  - compile
  - test
  - lint

compile:
  <<: *rust_template
  stage: compile
  script:
    - cargo build --all --verbose

test:
  <<: *rust_template
  stage: test
  script:
    - cargo test --all --verbose

fmt:
  <<: *rust_template
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

clippy:
  <<: *rust_template
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings
