image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

.rust_template: &rust_template
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends libzmq3-dev
    - rustc --version && cargo --version
    - cd rust-in-peace/
  only: 
    - merge_request
  cache:
    paths:
      - target/
      - cargo/

stages:
  - test
  - lint

test:
  <<: *rust_template
  stage: test
  script:
    - cargo test --all --verbose

fmt:
  <<: *rust_template
  stage: lint
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

clippy:
  <<: *rust_template
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings
