turns = 400
islands = 10
islands_sync = true
stats_path = "stats"

[network]
is_coordinator = true
hosts_num = 2
coordinator_ip = "127.0.0.1"
coordinator_rep_port = 4002
host_ip = "127.0.0.1"
pub_port = 5008
ips = ["127.0.0.1:6005", "127.0.0.1:6002"]

[network.global_sync]
sync = true
server_ip = "127.0.0.1"
server_rep_port = 7001
server_pub_port = 7002
