turns = 400
islands = 2
islands_sync = true

[network]
is_coordinator = true
hosts_num = 2
coordinator_ip = "127.0.0.1"
coordinator_rep_port = 4002
host_ip = "127.0.0.1"
pub_port = 5008
ips = ["127.0.0.1:6005", "127.0.0.1:6002"]

[island]
agents_number = 50

[agent_config]
minimum = true
initial_energy = 100
genotype_dim = 4
mutation_rate = 0.01
procreation_penalty = 0.5
procreation_prob = 70
meeting_penalty = 60
lower_bound = -5.12
upper_bound = 5.12
