turns = 1000
islands = 1

[container]
agents_number = 50

[agent]
minimum = true
genotype_dim = 50
mutation_rate = 0.01
procreation_penalty = 0.5
procreation_prob = 80
meeting_penalty = 60
lower_bound = -5.12
upper_bound = 5.12
