turns = 400
islands = 10
islands_sync = true
stats_path = "stats"

[network]
is_coordinator = false
hosts_num = 2
coordinator_ip = "127.0.0.1"
coordinator_rep_port = 4002
host_ip = "127.0.0.1"
pub_port = 6002
ips = ["127.0.0.1:6005", "127.0.0.1:5008"]

[network.global_sync]
sync = false
server_ip = "127.0.0.1"
server_rep_port = 7001
server_pub_port = 7002

[island]
agents_number = 50

[agent_config]
minimum = true
initial_energy = 100
genotype_dim = 4
mutation_rate = 0.01
procreation_penalty = 0.5
procreation_prob = 70
meeting_penalty = 60
lower_bound = -5.12
upper_bound = 5.12
