turns = 20
islands = 2

[container]
agents_number = 50

[agent_config]
minimum = true
initial_energy = 100
genotype_dim = 4
mutation_rate = 0.01
procreation_penalty = 0.5
procreation_prob = 70
meeting_penalty = 60
lower_bound = -5.12
upper_bound = 5.12
