[island_settings]
agents_number = 2
grass_interval = 30

[sheep_settings]
init_num = 120
init_energy = 10
reproduction_chance = 0.1
energy_gain = 4
energy_loss = 1

[wolf_settings]
init_num = 10
init_energy = 10
reproduction_chance = 0.1
energy_gain = 10
energy_loss = 3