{
 "title": "Rust In Peace - fun-opt",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Best fitness",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fitness_best" }
   ]
  },
  {
   "title": "All sent migraitons",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "migrations_sent_all" }
   ]
  },
  {
   "title": "Global sent migrations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "migrations_sent_glob" }
   ]
  },
  {
   "title": "Deads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "deads" }
   ]
  },
  {
   "title": "Local sent migrations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "migrations_sent_loc" }
   ]
  },
  {
   "title": "Procreations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "procreations" }
   ]
  },
  {
   "title": "Meetings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "meetings" }
   ]
  },
  {
   "title": "Total received messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "messages_recv_total" },
    {}
   ]
  }
 ]
}